CRITICAL - 2022-11-30 06:33:14 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 196, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(196): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen('r')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:33:40 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 196, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(196): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen('r')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:34:49 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 196, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(196): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen('r')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:36:13 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(150): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM2')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:36:22 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(150): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM1')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:36:34 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 196, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(196): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen('r')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:38:39 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 196, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(196): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:39:27 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(150): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM5')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:39:44 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 196, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(196): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:40:11 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(150): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:44:15 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 197, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(197): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:44:57 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 197, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(197): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:46:04 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 197, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(197): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen('r')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:46:21 --> Unable to open the device
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Unable to open ...', 'C:\\xampp\\htdocs...', 197, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(197): trigger_error('Unable to open ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(92): App\ThirdParty\phpSerial->deviceOpen('r')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:47:15 --> Reading serial port is not implemented for Windows
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Reading serial ...', 'C:\\xampp\\htdocs...', 562, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(562): trigger_error('Reading serial ...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(94): App\ThirdParty\phpSerial->readPort()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:52:38 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:52:57 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:53:25 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:53:41 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:54:18 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM2')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:54:25 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM1')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:54:32 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM4')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:54:43 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM5')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:54:53 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM6')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:23 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com1')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:28 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com1')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:32 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com2')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:36 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:39 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com5')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:51 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 06:56:59 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:01:37 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:02:53 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:02:59 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:03:08 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('\\\\.\\com3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:03:30 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:03:41 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:03:47 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:03:55 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:04:01 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(127): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:06:29 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 134, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(134): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:12:54 --> Undefined offset: 1
#0 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(100): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-11-30 07:12:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-11-30 07:13:22 --> Undefined offset: 1
#0 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(100): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-11-30 07:13:22 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-11-30 07:16:18 --> Specified serial port is not valid
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(512, 'Specified seria...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\ThirdParty\php_serial.class.php(150): trigger_error('Specified seria...', 512)
#2 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(86): App\ThirdParty\phpSerial->deviceSet('COM3')
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-30 07:33:55 --> Call to undefined function App\Controllers\dio_open()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:34:01 --> Call to undefined function App\Controllers\dio_open()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:37:30 --> Call to undefined function App\Controllers\dio_open()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:51:50 --> Use of undefined constant O_NOCTTY - assumed 'O_NOCTTY' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(108): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-11-30 07:52:07 --> Use of undefined constant O_NONBLOCK - assumed 'O_NONBLOCK' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(108): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-11-30 07:52:13 --> Call to undefined function App\Controllers\dio_fcntl()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:52:28 --> Call to undefined function App\Controllers\dio_tcsetattr()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:53:20 --> Use of undefined constant O_NOCTTY - assumed 'O_NOCTTY' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(108): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-11-30 07:53:34 --> Call to undefined function App\Controllers\dio_fcntl()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:54:12 --> dio_open() expects at least 2 parameters, 1 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dio_open() expe...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(108): dio_open('COM3')
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 07:56:25 --> Call to undefined function App\Controllers\dio_fcntl()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 07:57:35 --> dio_open(): cannot open file COM1 with flags 8 and permissions 0: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dio_open(): can...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(108): dio_open('COM1', 8)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 07:57:45 --> Call to undefined function App\Controllers\dio_fcntl()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 08:00:24 --> dio_open(): cannot open file COM3 with flags 8 and permissions 0: Permission denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dio_open(): can...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(108): dio_open('COM3', 8)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:02:48 --> Call to undefined function App\Controllers\dio_fcntl()
#0 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#1 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-11-30 08:09:37 --> dio_open(): cannot open file com3: with flags 8 and permissions 0: Permission denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dio_open(): can...', 'C:\\xampp\\htdocs...', 110, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(110): dio_open('com3:', 8)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:11:15 --> dio_open(): cannot open file com3: with flags 8 and permissions 0: Permission denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dio_open(): can...', 'C:\\xampp\\htdocs...', 110, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(110): dio_open('com3:', 8)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:13:08 --> dio_open(): cannot open file com3: with flags 8 and permissions 0: Permission denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'dio_open(): can...', 'C:\\xampp\\htdocs...', 110, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(110): dio_open('com3:', 8)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:17:19 --> fsockopen(): unable to connect to localhost:3400 (No connection could be made because the target machine actively refused it.
)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): un...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(127): fsockopen('localhost', 3400, 10061, 'No connection c...')
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:19:08 --> fsockopen(): unable to connect to localhost:3400 (No connection could be made because the target machine actively refused it.
)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): un...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(127): fsockopen('localhost', 3400, 10061, 'No connection c...')
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:25:08 --> fsockopen() expects parameter 2 to be int, string given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen() exp...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(127): fsockopen('localhost', 'com3', NULL, NULL)
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-11-30 08:25:40 --> fsockopen(): unable to connect to localhost:3400 (No connection could be made because the target machine actively refused it.
)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): un...', 'C:\\xampp\\htdocs...', 127, Array)
#1 C:\xampp\htdocs\wcs.pns.id\app\Controllers\Home.php(127): fsockopen('localhost', 3400, 10061, 'No connection c...')
#2 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->getSerial()
#3 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#4 C:\xampp\htdocs\wcs.pns.id\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\wcs.pns.id\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
